#!/bin/sh
gcc -O3 -march=native -fPIC -c -o ptiming.o ptiming.c
#gcc -ggdb3 -fPIC -c -o ptiming.o ptiming.c
ld -shared -o libptiming.so ptiming.o
gcc -O3 -march=native -o test_ptiming test_ptiming.c -L. -lptiming
